### ISSUE TITLE
Make an authorization plugin for GraphQL

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/graphql-authz#1]
See: https://casbin.org/docs/en/graphql-middlewares but this one is already deprecated. We may need to maintain our own now.

![image](https://user-images.githubusercontent.com/3787410/124505564-5efbf600-ddfc-11eb-8177-ca0e1435f269.png)

We may borrow some ideas from this one: https://github.com/maticzav/graphql-shield#features

This issue tries to help the issue from Galoy: https://github.com/GaloyMoney/galoy/issues/294

![image](https://user-images.githubusercontent.com/3787410/124505708-ad10f980-ddfc-11eb-84f4-01b8a01bee18.png)

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403 can anyone take this?

**Comment by Zxilly** [comment]
working on this

**Comment by Gabriel-403** [comment]
I see
