### ISSUE TITLE
Code coverage doesn't work

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/graphql-authz#4]
![image](https://user-images.githubusercontent.com/3787410/126054058-b29ed94a-d859-4e3c-a35e-a7cb7fbaaa49.png)

https://coveralls.io/github/node-casbin/graphql-authz

![image](https://user-images.githubusercontent.com/3787410/126054059-a477e260-01ce-49b4-b52c-62e2d9b480b0.png)

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
working on this
